### ISSUE TITLE
when load heketi.db, occur error

### ISSUE THREAD

**Issue by jianzi123** [heketi/heketi#1369]
### Kind of issue
Bug

### Observed behavior
```
Setting up heketi database
  File: /var/lib/heketi/heketi.db
  Size: 483328          Blocks: 944        IO Block: 4096   regular file
Device: fd01h/64769d    Inode: 918291      Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-09-25 01:56:25.617693066 +0000
Modify: 2018-09-25 01:56:25.565691458 +0000
Change: 2018-09-25 01:56:25.565691458 +0000
 Birth: -
total 20K
-rwx------ 1 root root 1.3K Mar  7  2018 ks-script-vo7zkv6o
-rwxrwxrwx 1 root root  16K Sep 25 02:01 heketi.db.gz
total 492K
-rwx------ 1 root root 1.3K Mar  7  2018 ks-script-vo7zkv6o
-rwxrwxrwx 1 root root  16K Sep 25 02:01 heketi.db.gz
-rwxrwxrwx 1 root root 472K Sep 25 02:01 heketi.db
Copied backup db to /var/lib/heketi/heketi.db
Heketi v7.0.0-5-gc10cbd1-release-7
[heketi] INFO 2018/09/25 02:01:37 Loaded kubernetes executor
[heketi] INFO 2018/09/25 02:01:37 open db.
[heketi] INFO 2018/09/25 02:01:37 opendb err: <nil>; dbfilename: /var/lib/heketi/heketi.db.
[heketi] INFO 2018/09/25 02:01:37 opendb not err, update.
[heketi] INFO 2018/09/25 02:01:37 update db
ERROR: Unable to start application
a: <nil>; err: invalid page type: 0: 0.
```

```
root@k8s-node2:~/heketi# ./heketi db export --dbfile heketi.db --jsonfile /tmp/q.json
panic: invalid page type: 0: 0

goroutine 1 [running]:
github.com/heketi/heketi/vendor/github.com/boltdb/bolt.(*Cursor).search(0xc4206c12e8, 0xc4206c1380, 0x6, 0x20, 0x55)
        /build/golang/src/github.com/heketi/heketi/vendor/github.com/boltdb/bolt/cursor.go:256 +0x40c
github.com/heketi/heketi/vendor/github.com/boltdb/bolt.(*Cursor).seek(0xc4206c12e8, 0xc4206c1380, 0x6, 0x20, 0x0, 0x0, 0x455500, 0xc4206c12c8, 0x420a48, 0x413756, ...)
        /build/golang/src/github.com/heketi/heketi/vendor/github.com/boltdb/bolt/cursor.go:159 +0xb1
github.com/heketi/heketi/vendor/github.com/boltdb/bolt.(*Bucket).Bucket(0xc42038c018, 0xc4206c1380, 0x6, 0x20, 0xc4206c1380)
        /build/golang/src/github.com/heketi/heketi/vendor/github.com/boltdb/bolt/bucket.go:112 +0xfc
github.com/heketi/heketi/vendor/github.com/boltdb/bolt.(*Tx).Bucket(0xc42038c000, 0xc4206c1380, 0x6, 0x20, 0x6)
        /build/golang/src/github.com/heketi/heketi/vendor/github.com/boltdb/bolt/tx.go:101 +0x4f
github.com/heketi/heketi/apps/glusterfs.EntryKeys(0xc42038c000, 0x189b26b, 0x6, 0x110, 0x110, 0x5)
        /build/golang/src/github.com/heketi/heketi/apps/glusterfs/dbentry.go:57 +0xbb
github.com/heketi/heketi/apps/glusterfs.VolumeList(0xc42038c000, 0x18a328b, 0xd, 0x0, 0x0, 0x0)
        /build/golang/src/github.com/heketi/heketi/apps/glusterfs/volume_entry.go:71 +0x44
github.com/heketi/heketi/apps/glusterfs.dbDumpInternal.func1(0xc42038c000, 0x19130b8, 0xc42038c000)
        /build/golang/src/github.com/heketi/heketi/apps/glusterfs/db_operations.go:38 +0xe3
github.com/heketi/heketi/vendor/github.com/boltdb/bolt.(*DB).View(0xc4203ce1e0, 0xc4206c1848, 0x0, 0x0)
        /build/golang/src/github.com/heketi/heketi/vendor/github.com/boltdb/bolt/db.go:626 +0x9a
github.com/heketi/heketi/apps/glusterfs.dbDumpInternal(0xc4203ce1e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffd93381839, ...)
        /build/golang/src/github.com/heketi/heketi/apps/glusterfs/db_operations.go:33 +0x2cd
github.com/heketi/heketi/apps/glusterfs.DbDump(0x7ffd93381839, 0xb, 0x7ffd93381819, 0x14, 0x0, 0x0)
        /build/golang/src/github.com/heketi/heketi/apps/glusterfs/db_operations.go:225 +0x1bf
main.glob..func3(0x25232e0, 0xc42007e2c0, 0x0, 0x4)
        /build/golang/src/github.com/heketi/heketi/main.go:113 +0x92
github.com/heketi/heketi/vendor/github.com/spf13/cobra.(*Command).execute(0x25232e0, 0xc42007e280, 0x4, 0x4, 0x25232e0, 0xc42007e280)
        /build/golang/src/github.com/heketi/heketi/vendor/github.com/spf13/cobra/command.go:651 +0x23d
github.com/heketi/heketi/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2522c80, 0x1822fc0, 0x16, 0x160000000020)
        /build/golang/src/github.com/heketi/heketi/vendor/github.com/spf13/cobra/command.go:726 +0x2fe
github.com/heketi/heketi/vendor/github.com/spf13/cobra.(*Command).Execute(0x2522c80, 0x7f90886104f0, 0x0)
        /build/golang/src/github.com/heketi/heketi/vendor/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
        /build/golang/src/github.com/heketi/heketi/main.go:286 +0x42
```

### Expected/desired behavior
start heketi

### Details on how to reproduce (minimal and precise)
restart heketi, do not know how to repoduce in details.

### Information about the environment:
- Heketi version used (e.g. v7.0.0 or master): 
  Heketi v7.0.0-5-gc10cbd1-release-7
- Operating system used: 
ubuntu-16.04
- Heketi compiled from sources, as a package (rpm/deb), or container: 
container
- If container, which container image: 
self create by Heketi v7.0.0
- Using kubernetes, openshift, or direct install: 
kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
inside kubernetes
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): 
custom

**Comment by phlogistonjohn** [comment]
Closing in favor of #1378
