### ISSUE TITLE
boltdb access failed during get node info

### ISSUE THREAD

**Issue by Madhu-1** [heketi/heketi#1378]
### Kind of issue

Bug

### Observed behavior
heketi is not  sending a response which I do get node info

### Expected/desired behavior
Heketi should respond node information

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): v7.0.0
- Operating system used: 
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): 

### Other useful information

Logs:

```
[negroni] Started GET /nodes/345438b215c947a8e2d9ab1c08e41608
[negroni] PANIC: invalid page type: 3: 10
goroutine 687 [running]:
github.com/urfave/negroni.(*Recovery).ServeHTTP.func1(0x7f500ae62720, 0xc42021d400, 0xc4204afc80)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/urfave/negroni/recovery.go:34 +0xef
panic(0x164a020, 0xc42027ff80)
	/usr/lib/golang/src/runtime/panic.go:491 +0x283
github.com/boltdb/bolt.(*Cursor).search(0xc420541090, 0xc4205410f8, 0x20, 0x20, 0x3)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/boltdb/bolt/cursor.go:256 +0x40c
github.com/boltdb/bolt.(*Cursor).seek(0xc420541090, 0xc4205410f8, 0x20, 0x20, 0x0, 0x0, 0x8f69d0, 0xc420175438, 0xc42012b3a0, 0x1, ...)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/boltdb/bolt/cursor.go:159 +0xb1
github.com/boltdb/bolt.(*Bucket).Get(0xc42021db80, 0xc4205410f8, 0x20, 0x20, 0x20, 0x20, 0x0)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/boltdb/bolt/bucket.go:260 +0xe6
github.com/heketi/heketi/apps/glusterfs.EntryLoad(0xc420175420, 0x246c9c0, 0xc4203e4880, 0xc420352980, 0x20, 0x0, 0x1)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/heketi/heketi/apps/glusterfs/dbentry.go:135 +0x155
github.com/heketi/heketi/apps/glusterfs.NewDeviceEntryFromId(0xc420175420, 0xc420352980, 0x20, 0x25026b8, 0x0, 0x0)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/heketi/heketi/apps/glusterfs/device_entry.go:75 +0x118
github.com/heketi/heketi/apps/glusterfs.(*NodeEntry).NewInfoReponse(0xc42045aa20, 0xc420175420, 0x20, 0xc42045aa20, 0x0)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/heketi/heketi/apps/glusterfs/node_entry.go:399 +0x215
github.com/heketi/heketi/apps/glusterfs.(*App).NodeInfo.func1(0xc420175420, 0x191fd28, 0xc420175420)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/heketi/heketi/apps/glusterfs/app_node.go:195 +0xa1
github.com/boltdb/bolt.(*DB).View(0xc4204c41e0, 0xc4207713a0, 0x0, 0x0)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/boltdb/bolt/db.go:626 +0x9a
github.com/heketi/heketi/apps/glusterfs.(*App).NodeInfo(0xc4202db380, 0x7f500ae62720, 0xc42021d400, 0xc4206aa400)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/heketi/heketi/apps/glusterfs/app_node.go:185 +0xf2
github.com/heketi/heketi/apps/glusterfs.(*App).NodeInfo-fm(0x7f500ae62720, 0xc42021d400, 0xc4206aa400)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/heketi/heketi/apps/glusterfs/app.go:412 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42024fc20, 0x7f500ae62720, 0xc42021d400, 0xc4206aa400)
	/usr/lib/golang/src/net/http/server.go:1918 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc420350870, 0x7f500ae62720, 0xc42021d400, 0xc4206aa400)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/gorilla/mux/mux.go:114 +0xdc
github.com/urfave/negroni.Wrap.func1(0x7f500ae62720, 0xc42021d400, 0xc4206aa200, 0xc42012aba0)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/urfave/negroni/negroni.go:41 +0x4d
github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc4203ef3c0, 0x7f500ae62720, 0xc42021d400, 0xc4206aa200, 0xc42012aba0)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/urfave/negroni/negroni.go:24 +0x4e
github.com/urfave/negroni.middleware.ServeHTTP(0x2466480, 0xc4203ef3c0, 0xc4203ef480, 0x7f500ae62720, 0xc42021d400, 0xc4206aa200)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/urfave/negroni/negroni.go:33 +0xa5
github.com/urfave/negroni.(middleware).ServeHTTP-fm(0x7f500ae62720, 0xc42021d400, 0xc4206aa200)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/urfave/negroni/negroni.go:33 +0x60
github.com/heketi/heketi/server/admin.(*ServerState).ServeHTTP(0xc420333dd0, 0x7f500ae62720, 0xc42021d400, 0xc4206aa200, 0xc42012ab80)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/heketi/heketi/server/admin/http.go:55 +0x69
github.com/urfave/negroni.middleware.ServeHTTP(0x245e740, 0xc420333dd0, 0xc4203ef460, 0x7f500ae62720, 0xc42021d400, 0xc4206aa200)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/urfave/negroni/negroni.go:33 +0xa5
github.com/urfave/negroni.(middleware).ServeHTTP-fm(0x7f500ae62720, 0xc42021d400, 0xc4206aa200)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/urfave/negroni/negroni.go:33 +0x60
github.com/heketi/heketi/apps/glusterfs.(*App).Auth(0xc4202db380, 0x7f500ae62720, 0xc42021d400, 0xc4206aa200, 0xc42012ab60)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/heketi/heketi/apps/glusterfs/app_middleware.go:45 +0x126
github.com/heketi/heketi/apps/glusterfs.(*App).Auth-fm(0x7f500ae62720, 0xc42021d400, 0xc4206aa200, 0xc42012ab60)
	/builddir/build/BUILD/heketi-7.0.0/main.go:371 +0x52
github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc42027f3a0, 0x7f500ae62720, 0xc42021d400, 0xc4206aa200, 0xc42012ab60)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/urfave/negroni/negroni.go:24 +0x4e
github.com/urfave/negroni.middleware.ServeHTTP(0x2466480, 0xc42027f3a0, 0xc4203ef440, 0x7f500ae62720, 0xc42021d400, 0xc4206aa200)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/urfave/negroni/negroni.go:33 +0xa5
github.com/urfave/negroni.(middleware).ServeHTTP-fm(0x7f500ae62720, 0xc42021d400, 0xc4206aa200)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/urfave/negroni/negroni.go:33 +0x60
github.com/heketi/heketi/middleware.(*JwtAuth).ServeHTTP(0xc420333da0, 0x7f500ae62720, 0xc42021d400, 0xc4206aa200, 0xc42012aaa0)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/heketi/heketi/middleware/jwt.go:193 +0x48d
github.com/urfave/negroni.middleware.ServeHTTP(0x245e680, 0xc420333da0, 0xc4203ef420, 0x7f500ae62720, 0xc42021d400, 0xc4206aa200)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/urfave/negroni/negroni.go:33 +0xa5
github.com/urfave/negroni.(middleware).ServeHTTP-fm(0x7f500ae62720, 0xc42021d400, 0xc4206aa200)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/urfave/negroni/negroni.go:33 +0x60
github.com/urfave/negroni.(*Logger).ServeHTTP(0xc4204865a8, 0x7f500ae62720, 0xc42021d400, 0xc4206aa200, 0xc42012aa80)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/urfave/negroni/logger.go:25 +0x16d
github.com/urfave/negroni.middleware.ServeHTTP(0x245e7c0, 0xc4204865a8, 0xc4203ef400, 0x7f500ae62720, 0xc42021d400, 0xc4206aa200)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/urfave/negroni/negroni.go:33 +0xa5
github.com/urfave/negroni.(middleware).ServeHTTP-fm(0x7f500ae62720, 0xc42021d400, 0xc4206aa200)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/urfave/negroni/negroni.go:33 +0x60
github.com/urfave/negroni.(*Recovery).ServeHTTP(0xc4204afc80, 0x7f500ae62720, 0xc42021d400, 0xc4206aa200, 0xc42012aa60)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/urfave/negroni/recovery.go:45 +0x82
github.com/urfave/negroni.middleware.ServeHTTP(0x245e840, 0xc4204afc80, 0xc4203ef3e0, 0x7f500ae62720, 0xc42021d400, 0xc4206aa200)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/urfave/negroni/negroni.go:33 +0xa5
github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc4203888d0, 0x24765c0, 0xc420175340, 0xc4206aa200)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/urfave/negroni/negroni.go:73 +0x100
github.com/gorilla/mux.(*Router).ServeHTTP(0xc420350730, 0x24765c0, 0xc420175340, 0xc4206aa200)
	/builddir/build/BUILD/heketi-7.0.0/src/github.com/gorilla/mux/mux.go:114 +0xdc
net/http.serverHandler.ServeHTTP(0xc420355ba0, 0x24765c0, 0xc420175340, 0xc4206aa000)
	/usr/lib/golang/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc42022d540, 0x2477800, 0xc42021cfc0)
	/usr/lib/golang/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/lib/golang/src/net/http/server.go:2720 +0x288
```

**Comment by Madhu-1** [comment]
node list response from heketi
```
[root@cns-master ~]# heketi-cli node list --user=admin --secret=adminkey -s http://172.31.194.213:8080
Id:345438b215c947a8e2d9ab1c08e41608	Cluster:52fc41ebaf20f8dc6043f7e0039d1942
Id:444d5ac0f2a3e741d602e4e79f885db2	Cluster:52fc41ebaf20f8dc6043f7e0039d1942
Id:fb9b8d561b56c9e2fe4ef75f11371f9c	Cluster:52fc41ebaf20f8dc6043f7e0039d1942
```

**Comment by phlogistonjohn** [comment]
Bolt db level corruption. There's nothing heketi can do recover from this situation. If this is still a problem I recommend trying to scrape the relevant data from the corrupted db and create a new db with the data (from json). I have done it so I know it can be done, however it is challenging and I can offer no specific assistance at this time.
Closing as "cantfix".
