### ISSUE TITLE
core dump when brick replacement

### ISSUE THREAD

**Issue by danielzhanghl** [heketi/heketi#1900]
### Kind of issue

Bug

### Observed behavior
in our environment, there is node failure happened and need to remove the node, and core dump happened when brick replacement, from glusterfs side, the old brick(on the failure node) is gone and new brick(on the ok node) is up, seems the error happened when heketi try to update its boltdb, and core dump appears.

after this error, the process is restarted, and once we try to remove the failure node again, heketi will retrieve the bricks map from glusterfs, since the new bricks is not updated to its boltdb, heketi will report error("Id not found") and can't proceed.

thanks for looking into this.

core dump is as below:
"panic: runtime error: invalid memory address or nil pointer dereference"
"[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x10f4bf8]"

"goroutine 21145 [running]:"}
"github.com/heketi/heketi/apps/glusterfs.(*removeBrickComboOperation).Finalize.func1(0xc00aa24a80, 0x0, 0x0)"
/build/golang/src/github.com/heketi/heketi/apps/glusterfs/operations_device.go:1001 +0x268"
"github.com/heketi/heketi/vendor/github.com/boltdb/bolt.(*DB).Update(0xc00000c1e0, 0xc001db74a0, 0x0, 0x0)"
/build/golang/src/github.com/heketi/heketi/vendor/github.com/boltdb/bolt/db.go:598 +0x8e"
"github.com/heketi/heketi/apps/glusterfs.(*removeBrickComboOperation).Finalize(0xc007225d30, 0x1627be0, 0xc0000b8dc0)"
/build/golang/src/github.com/heketi/heketi/apps/glusterfs/operations_device.go:987 +0x90"
"github.com/heketi/heketi/apps/glusterfs.runOperationAfterBuild(0x1615ba0, 0xc007225d30, 0x1627be0, 0xc0000b8dc0, 0xc00006ce00, 0x7f0b8ea7ee98)"
/build/golang/src/github.com/heketi/heketi/apps/glusterfs/operations_manage.go:199 +0x762"
"github.com/heketi/heketi/apps/glusterfs.RunOperation(0x1615ba0, 0xc007225d30, 0x1627be0, 0xc0000b8dc0, 0x0, 0x0)"
/build/golang/src/github.com/heketi/heketi/apps/glusterfs/operations_manage.go:261 +0x2a3"
"github.com/heketi/heketi/apps/glusterfs.(*DeviceRemoveOperation).migrateBricks(0xc0024dfa80, 0x1627be0, 0xc0000b8dc0, 0xc0005348f0, 0x0, 0x40bd7b)"
/build/golang/src/github.com/heketi/heketi/apps/glusterfs/operations_device.go:166 +0x1e7"
"github.com/heketi/heketi/apps/glusterfs.(*DeviceRemoveOperation).Exec(0xc0024dfa80, 0x1627be0, 0xc0000b8dc0, 0xc0030540f0, 0xc000246c40)"
/build/golang/src/github.com/heketi/heketi/apps/glusterfs/operations_device.go:152 +0x16c"
"github.com/heketi/heketi/apps/glusterfs.runOperationAfterBuild(0x1615960, 0xc0024dfa80, 0x1627be0, 0xc0000b8dc0, 0xc000600000, 0x7f0b8ea7ee98)"
/build/golang/src/github.com/heketi/heketi/apps/glusterfs/device_entry.go:399 +0xf7"
"github.com/heketi/heketi/apps/glusterfs.(*DeviceEntry).SetState(0xc0005cc630, 0x15ec960, 0xc00000c1e0, 0x1627be0, 0xc0000b8dc0, 0xc00310f548, 0x6, 0x0, 0x0, 0xc88d7a72863
/build/golang/src/github.com/heketi/heketi/apps/glusterfs/device_entry.go:175 +0x19b"
"github.com/heketi/heketi/apps/glusterfs.(*App).DeviceSetState.func2(0x0, 0x0, 0x0, 0x0)"
/build/golang/src/github.com/heketi/heketi/apps/glusterfs/app_device.go:353 +0xfa"
"github.com/heketi/heketi/server/rest.(*AsyncHttpHandler).handle.func1(0xc001facd80, 0xc001facd00)"
/build/golang/src/github.com/heketi/heketi/server/rest/asynchttp.go:286 +0xc5"
"created by github.com/heketi/heketi/server/rest.(*AsyncHttpHandler).handle"
/build/golang/src/github.com/heketi/heketi/server/rest/asynchttp.go:282 +0x49"

the error when try again is:
ERROR 2022/05/05 13:30:08 heketi/apps/glusterfs/volume_entry_allocate.go:119:glusterfs.(*VolumeEntry).getBrickSetForBrickId: Unable to create brick entry using brick name:172.16.4.11:/var/lib/heketi/mounts/vg_10756ec1d5355fd5b339c54d2c290866/brick_e22c00c369f38ea94a114952ab6f775e/brick"
heketi/apps/glusterfs/operations_manage.go:167:glusterfs.runOperationAfterBuild: Remove Brick from Device Failed: Id not found"

 

### Expected/desired behavior
when update db failure happens, there should no core dump, and heketi could retry, while right now it's stuck. 

### Details on how to reproduce (minimal and precise)
it's not happened always, only when update the db failure

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master):  Heketi v10.1.0

- Operating system used:  centos
- Heketi compiled from sources, as a package (rpm/deb), or container:  heketi in container.
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by danielzhanghl** [comment]
no one maintain this project now, just close it.
