### ISSUE TITLE
golang panic when running `heketi-cli load <topology.json-file>`

### ISSUE THREAD

**Issue by jeffvance** [heketi/heketi#445]
go panic:
=======
```
# heketi-cli topology load --json=erin-topo.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x469d25]

goroutine 1 [running]:
panic(0xc6b280, 0xc82000e0e0)
	/usr/lib/golang/src/runtime/panic.go:481 +0x3e6
github.com/heketi/heketi/client/cli/go/cmds.getNodeIdFromHeketiTopology(0x0, 0xc8201c6820, 0xc, 0xc820126f60)
	/builddir/build/BUILD/heketi-dd29da6/src/github.com/heketi/heketi/client/cli/go/cmds/topology.go:70 +0x2c5
github.com/heketi/heketi/client/cli/go/cmds.glob.func17(0x13f5800, 0xc8201c66f0, 0x0, 0x1, 0x0, 0x0)
	/builddir/build/BUILD/heketi-dd29da6/src/github.com/heketi/heketi/client/cli/go/cmds/topology.go:137 +0x89b
github.com/spf13/cobra.(*Command).execute(0x13f5800, 0xc8201c6680, 0x1, 0x1, 0x0, 0x0)
	/builddir/build/BUILD/heketi-dd29da6/Godeps/_workspace/src/github.com/spf13/cobra/command.go:568 +0x62c
github.com/spf13/cobra.(*Command).ExecuteC(0x13f5400, 0x13f5800, 0x0, 0x0)
	/builddir/build/BUILD/heketi-dd29da6/Godeps/_workspace/src/github.com/spf13/cobra/command.go:662 +0x53f
github.com/spf13/cobra.(*Command).Execute(0x13f5400, 0x0, 0x0)
	/builddir/build/BUILD/heketi-dd29da6/Godeps/_workspace/src/github.com/spf13/cobra/command.go:618 +0x2d
main.main()
	/builddir/build/BUILD/heketi-dd29da6/client/cli/go/main.go:35 +0xe0
```

JSON file:
```
# cat erin-topo.json  #passes several json validators
{
    "clusters": [
        {
            "nodes": [
                {
                    "node": {
                        "hostnames": {
                            "manage": [
                                "aplo-rhel7.2"
                            ],
                            "storage": [
                                "192.168.122.10"
                            ]
                        },
                        "zone": 1
                    },
                    "devices": [
                        "/dev/vdc"
                    ]
                },
                {
                    "node": {
                        "hostnames": {
                            "manage": [
                                "aplo-rhel7.2-node1"
                            ],
                            "storage": [
                                "192.168.122.181"
                            ]
                        },
                        "zone": 1
                    },
                    "devices": [
                        "/dev/vdc"
                    ]
                },
                {
                    "node": {
                        "hostnames": {
                            "manage": [
                                "aplo-rhel7.2-node2"
                            ],
                            "storage": [
                                "192.168.122.151"
                            ]
                        },
                        "zone": 2
                    },
                    "devices": [
                        "/dev/vdc"
                    ]
                }
        ]
        }
    ]
}
```

Info from `oc` command:
```
# oc whoami
admin

# oc project
Using project "jeff" on server "https://192.168.122.10:8443".

# oc get node
NAME                 STATUS    AGE
aplo-rhel7.2         Ready     5d
aplo-rhel7.2-node1   Ready     5d
aplo-rhel7.2-node2   Ready     5d

# oc get dc
NAME                              REVISION   REPLICAS   TRIGGERED BY
aplo-router                       1          1          config
deploy-heketi                     1          1          config
glusterfs-dc-aplo-rhel7.2         1          1          config
glusterfs-dc-aplo-rhel7.2-node1   1          1          config
glusterfs-dc-aplo-rhel7.2-node2   1          1          config

# oc get rc
NAME                                DESIRED   CURRENT   AGE
aplo-router-1                       1         1         1d
deploy-heketi-1                     1         1         2h
glusterfs-dc-aplo-rhel7.2-1         1         1         1d
glusterfs-dc-aplo-rhel7.2-node1-1   1         1         1d
glusterfs-dc-aplo-rhel7.2-node2-1   1         1         1d

# oc get svc
NAME            CLUSTER-IP      EXTERNAL-IP   PORT(S)                   AGE
aplo-router     172.30.71.166   <none>        80/TCP,443/TCP,1936/TCP   1d
deploy-heketi   172.30.29.166   <none>        8080/TCP                  2h

# oc get templates
NAME            DESCRIPTION                               PARAMETERS    OBJECTS
deploy-heketi   Bootstrap Heketi installation             8 (7 blank)   3
glusterfs       GlusterFS container deployment template   1 (1 blank)   1
heketi          Heketi service deployment template        8 (7 blank)   3

# oc get route
NAME            HOST/PORT                                    PATH      SERVICE         TERMINATION   LABELS
deploy-heketi   deploy-heketi-jeff.cloudapps.mystorage.com             deploy-heketi                 deploy-heketi=support,glusterfs=heketi-route,template=deploy-heketi

# oc get pod -o wide
NAME                                      READY     STATUS    RESTARTS   AGE       NODE
aplo-router-1-m5dxx                       1/1       Running   1          1d        aplo-rhel7.2
deploy-heketi-1-ym695                     1/1       Running   0          2h        aplo-rhel7.2
glusterfs-dc-aplo-rhel7.2-1-yx1qr         1/1       Running   0          1d        aplo-rhel7.2
glusterfs-dc-aplo-rhel7.2-node1-1-kilrf   1/1       Running   0          1d        aplo-rhel7.2-node1
glusterfs-dc-aplo-rhel7.2-node2-1-6nsg7   1/1       Running   0          1d        aplo-rhel7.2-node2

# oc logs deploy-heketi-1-ym695
Heketi 2.0.6
[heketi] INFO 2016/08/02 17:04:22 Loaded kubernetes executor
[heketi] INFO 2016/08/02 17:04:23 Loaded simple allocator
[heketi] INFO 2016/08/02 17:04:23 GlusterFS Application Loaded
Listening on port 8080

# oc describe pod deploy-heketi-1-ym695
Name:		deploy-heketi-1-ym695
Namespace:	jeff
Node:		aplo-rhel7.2/192.168.122.10
Start Time:	Tue, 02 Aug 2016 15:05:08 -0400
Labels:		deploy-heketi=support,deployment=deploy-heketi-1,deploymentconfig=deploy-heketi,glusterfs=heketi-pod,name=deploy-heketi
Status:		Running
IP:		10.1.1.2
Controllers:	ReplicationController/deploy-heketi-1
Containers:
  deploy-heketi:
    Container ID:	docker://160bc61e5d900c29871684a9b2037151c4baf4729ac0394f7eaf16d1354c0a68
    Image:		registry.access.stage.redhat.com/rhgs3/rhgs-volmanager-rhel7
    Image ID:		docker://sha256:c010855f4be100690054b83bc6823cc87f29fe2a781bd4dacdf2a59097401743
    Port:		8080/TCP
    QoS Tier:
      cpu:		BestEffort
      memory:		BestEffort
    State:		Running
      Started:		Tue, 02 Aug 2016 17:04:22 -0400
    Ready:		True
    Restart Count:	0
    Liveness:		http-get http://:8080/hello delay=30s timeout=3s period=10s #success=1 #failure=3
    Readiness:		http-get http://:8080/hello delay=3s timeout=3s period=10s #success=1 #failure=3
    Environment Variables:
      HEKETI_USER_KEY:		
      HEKETI_ADMIN_KEY:		
      HEKETI_EXECUTOR:		kubernetes
      HEKETI_FSTAB:		/var/lib/heketi/fstab
      HEKETI_KUBE_CERTFILE:	
      HEKETI_KUBE_INSECURE:	y
      HEKETI_KUBE_USER:		admin
      HEKETI_KUBE_PASSWORD:	admin
      HEKETI_KUBE_NAMESPACE:	jeff
      HEKETI_KUBE_APIHOST:	https://aplo-rhel7.2:8443
Conditions:
  Type		Status
  Ready 	True 
Volumes:
  db:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	
  default-token-hmxzr:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-hmxzr
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason	Message
  ---------	--------	-----	----			-------------	--------	------	-------
  6m		6m		1	{kubelet aplo-rhel7.2}	spec.containers{deploy-heketi}	Normal		Pulling	pulling image "registry.access.stage.redhat.com/rhgs3/rhgs-volmanager-rhel7"
  6m		6m		1	{kubelet aplo-rhel7.2}	spec.containers{deploy-heketi}	Normal		Pulled	Successfully pulled image "registry.access.stage.redhat.com/rhgs3/rhgs-volmanager-rhel7"
  6m		6m		1	{kubelet aplo-rhel7.2}	spec.containers{deploy-heketi}	Normal		Created	Created container with docker id 160bc61e5d90
  6m		6m		1	{kubelet aplo-rhel7.2}	spec.containers{deploy-heketi}	Normal		Started	Started container with docker id 160bc61e5d90
```

Curl:
```
# curl http://deploy-heketi-jeff.cloudapps.mystorage.com/hello
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <style type="text/css">
  /*!
   * Bootstrap v3.3.5 (http://getbootstrap.com)
  ...
```

Env variables on master:
```
# env|grep HEKETI
HEKETI_CLI_SERVER=http://deploy-heketi-jeff.cloudapps.mystorage.com
```

**Comment by lpabon** [comment]
Issue is caused by data returned from a server which is not Heketi, and it panics on https://github.com/heketi/heketi/blob/master/client/cli/go/cmds/topology.go#L70

**Comment by lpabon** [comment]
Here is the real issue:  https://github.com/heketi/heketi/blob/master/client/cli/go/cmds/topology.go#L128 .

err is set but not used.

**Comment by jeffvance** [comment]
Good find!

----- Original Message -----

**Comment by lpabon** [comment]
Again found:

```
TASK [client : install topology in deploy-heketi] ******************************
fatal: [client]: FAILED! => {"changed": true, "cmd": ["heketi-cli", "-s", "http://deploy-heketi-default.cloudapps.example.com", "topology", "load", "--json=topology.json"], "delta": "0:00:00.027980", "end": "2016-09-09 20:55:28.390855", "failed": true, "rc": 2, "start": "2016-09-09 20:55:28.362875", "stderr": "panic: runtime error: invalid memory address or nil pointer dereference\n[signal 0xb code=0x1 addr=0x0 pc=0x469d85]\n\ngoroutine 1 [running]:\npanic(0xe5a4a0, 0xc8200100c0)\n\t/usr/lib/golang/src/runtime/panic.go:481 +0x3e6\ngithub.com/heketi/heketi/client/cli/go/cmds.getNodeIdFromHeketiTopology(0x0, 0xc820359e20, 0xe, 0xc820378140)\n\t/root/go/src/github.com/heketi/heketi/client/cli/go/cmds/topology.go:70 +0x2c5\ngithub.com/heketi/heketi/client/cli/go/cmds.glob.func17(0x1770d20, 0xc82036c180, 0x0, 0x3, 0x0, 0x0)\n\t/root/go/src/github.com/heketi/heketi/client/cli/go/cmds/topology.go:137 +0x89b\ngithub.com/heketi/heketi/vendor/github.com/spf13/cobra.(*Command).execute(0x1770d20, 0xc8202be600, 0x3, 0x4, 0x0, 0x0)\n\t/root/go/src/github.com/heketi/heketi/vendor/github.com/spf13/cobra/command.go:599 +0x668\ngithub.com/heketi/heketi/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x17708e0, 0x1770d20, 0x0, 0x0)\n\t/root/go/src/github.com/heketi/heketi/vendor/github.com/spf13/cobra/command.go:689 +0x55c\ngithub.com/heketi/heketi/vendor/github.com/spf13/cobra.(*Command).Execute(0x17708e0, 0x0, 0x0)\n\t/root/go/src/github.com/heketi/heketi/vendor/github.com/spf13/cobra/command.go:648 +0x2d\nmain.main()\n\t/root/go/src/github.com/heketi/heketi/client/cli/go/main.go:35 +0xe0", "stdout": "", "stdout_lines": [], "warnings": []
```
https://ci.centos.org/job/gluster_heketi-functional/67/consoleFull
