### ISSUE TITLE
Documentation for building from source

### ISSUE THREAD

**Issue by naisanza** [heketi/heketi#672]
**Update:** This works for Ubuntu 16.04 and 16.10
```
export GOPATH=~/heketi
mkdir -p $GOPATH/src/github.com/heketi
cd $GOPATH/src/github.com/heketi
git clone https://github.com/heketi/heketi.git
cd heketi
#go get github.com/tools/godep
cd /usr/local/bin
wget -O godep https://github.com/tools/godep/releases/download/v79/godep_linux_amd64
chmod +x /usr/local/bin/godep
```

Instructions for building heketi-server from source should be added to the documentation, including dependencies

https://github.com/heketi/heketi/wiki/Running-the-server

* [x] godep 
```
wget -O godep https://github.com/tools/godep/releases/download/v79/godep_linux_amd64
chmod +x godep
mv godep /usr/local/bin/
```
* [x] git 
``` 
apt install -y git
```
* [x] go  
```
apt install -y golang
```
* [x] github.com/codegangsta/negroni 
```
mkdir -p $GOPATH/src/github.com/codegangsta/negroni
cd $GOPATH/src/github.com/codegangsta
git clone https://github.com/urfave/negroni.git
```
* [x] github.com/gorilla/mux
```
mkdir -p $GOPATH/src/github.com/gorilla/mux
cd $GOPATH/src/github.com/gorilla
git clone https://github.com/gorilla/mux.git
```
* [x] github.com/heketi/heketi/apps, glusterfs, middleware
```
mkdir -p $GOPATH/src/github.com/heketi/heketi
cd $GOPATH/src/github.com/heketi
git clone https://github.com/heketi/heketi.git
```
* [x] github.com/gorilla/context
```
mkdir -p $GOPATH/src/github.com/gorilla/context
cd $GOPATH/src/github.com/gorilla
git clone https://github.com/gorilla/context.git
```

install.sh:
```
export GOPATH=~/heketi 

wget -O godep https://github.com/tools/godep/releases/download/v79/godep_linux_amd64
chmod +x godep
mv godep /usr/local/bin/

apt install -y git

apt install -y golang

mkdir -p $GOPATH/src/github.com/codegangsta/negroni
cd $GOPATH/src/github.com/codegangsta
git clone https://github.com/urfave/negroni.git

mkdir -p $GOPATH/src/github.com/gorilla/mux
cd $GOPATH/src/github.com/gorilla
git clone https://github.com/gorilla/mux.git

mkdir -p $GOPATH/src/github.com/heketi/heketi
cd $GOPATH/src/github.com/heketi
git clone https://github.com/heketi/heketi.git

mkdir -p $GOPATH/src/github.com/gorilla/context
cd $GOPATH/src/github.com/gorilla
git clone https://github.com/gorilla/context.git
```

error:
```
root@gluster01-portal:~/heketi-3.1.0# make
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
godep go build -ldflags "-X main.HEKETI_VERSION=- -extldflags '-z relro -z now'" -o heketi
godep: [WARNING]: godep should only be used inside a valid go package directory and
godep: [WARNING]: may not function correctly. You are probably outside of your $GOPATH.
godep: [WARNING]:       Current Directory: $GOPATH
godep: [WARNING]:       $GOPATH: 
godep: WARNING: Godep workspaces (./Godeps/_workspace) are deprecated and support for them will be removed when go1.8 is released.
godep: WARNING: Go version (go1.6) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists
# _$GOPATH
./main.go:139: cannot use heketiRouter (type *"github.com/gorilla/mux".Router) as type *"github.com/heketi/heketi/vendor/github.com/gorilla/mux".Router in argument to app.SetRoutes
godep: go exit status 2
Makefile:55: recipe for target 'server' failed
make: *** [server] Error 1
```

From https://github.com/heketi/heketi/wiki/Development-Guide

go.sh:
```
export GOPATH=~/heketi
mkdir -p $GOPATH/src/github.com/heketi
cd $GOPATH/src/github.com/heketi
git clone https://github.com/heketi/heketi.git
cd heketi
go get github.com/tools/godep
```

Error:
```
root@gluster01-portal:~/heketi/src/github.com/heketi/heketi# make server
godep go build -ldflags "-X main.HEKETI_VERSION=v3.0.0-102-g8a79fb3 -extldflags '-z relro -z now'" -o heketi
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x93e400, 0xc8200100c0)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
main.vendoredImportPath(0xc820475400, 0xc8203da3c1, 0x1a, 0x0, 0x0)
        /usr/lib/go-1.6/src/cmd/go/pkg.go:466 +0x713
main.loadImport(0xc8203da3c1, 0x1a, 0xc82036ff90, 0x47, 0xc820475400, 0xc8201b1750, 0xc82032ce70, 0x1, 0x1, 0x1, ...)
        /usr/lib/go-1.6/src/cmd/go/pkg.go:336 +0xe52
main.(*Package).load(0xc820475400, 0xc8201b1750, 0xc82041b500, 0x0, 0x0, 0x4)
        /usr/lib/go-1.6/src/cmd/go/pkg.go:953 +0x4397
main.loadImport(0xc8201a0761, 0x16, 0xc820159ce0, 0x29, 0xc82017f000, 0xc8201b1750, 0xc8201a49f0, 0x1, 0x1, 0x1, ...)
        /usr/lib/go-1.6/src/cmd/go/pkg.go:377 +0x84e
main.(*Package).load(0xc82017f000, 0xc8201b1750, 0xc820181500, 0x0, 0x0, 0xc)
        /usr/lib/go-1.6/src/cmd/go/pkg.go:953 +0x4397
main.loadImport(0x9e1b98, 0x1, 0xc820016034, 0x29, 0x0, 0xc8201b1750, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/lib/go-1.6/src/cmd/go/pkg.go:377 +0x84e
main.loadPackage(0x9e1b98, 0x1, 0xc8201b1750, 0x0)
        /usr/lib/go-1.6/src/cmd/go/pkg.go:1639 +0x13d8
main.packagesAndErrors(0xc8201868e0, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go-1.6/src/cmd/go/pkg.go:1684 +0x531
main.packagesForBuild(0xc82000a110, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go-1.6/src/cmd/go/pkg.go:1700 +0x82
main.runBuild(0xc8aca0, 0xc82000a110, 0x0, 0x0)
        /usr/lib/go-1.6/src/cmd/go/build.go:442 +0x8d
main.main()
        /usr/lib/go-1.6/src/cmd/go/main.go:181 +0x783
godep: go exit status 2
Makefile:55: recipe for target 'server' failed
make: *** [server] Error 1
```

**Comment by lpabon** [comment]
I'm not sure if the user should build the server before running it.  They can use the container or yum to install it.  I did notice the error above which you have highlighted on #674 .
