### ISSUE TITLE
Error: make server

### ISSUE THREAD

**Issue by naisanza** [heketi/heketi#674]
I followed the steps in https://github.com/heketi/heketi/wiki/Development-Guide, but I'm unable to `make server` without getting a build error that I don't know what it means

```
export GOPATH=~/heketi
mkdir -p $GOPATH/src/github.com/heketi
cd $GOPATH/src/github.com/heketi
git clone https://github.com/heketi/heketi.git
cd heketi
go get github.com/tools/godep
```

```
root@gluster01-portal:~/heketi/src/github.com/heketi/heketi# make server
godep go build -ldflags "-X main.HEKETI_VERSION=v3.0.0-102-g8a79fb3 -extldflags '-z relro -z now'" -o heketi
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x93e400, 0xc8200100c0)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
main.vendoredImportPath(0xc820475400, 0xc8203da3c1, 0x1a, 0x0, 0x0)
        /usr/lib/go-1.6/src/cmd/go/pkg.go:466 +0x713
main.loadImport(0xc8203da3c1, 0x1a, 0xc82036ff90, 0x47, 0xc820475400, 0xc8201b1750, 0xc82032ce70, 0x1, 0x1, 0x1, ...)
        /usr/lib/go-1.6/src/cmd/go/pkg.go:336 +0xe52
main.(*Package).load(0xc820475400, 0xc8201b1750, 0xc82041b500, 0x0, 0x0, 0x4)
        /usr/lib/go-1.6/src/cmd/go/pkg.go:953 +0x4397
main.loadImport(0xc8201a0761, 0x16, 0xc820159ce0, 0x29, 0xc82017f000, 0xc8201b1750, 0xc8201a49f0, 0x1, 0x1, 0x1, ...)
        /usr/lib/go-1.6/src/cmd/go/pkg.go:377 +0x84e
main.(*Package).load(0xc82017f000, 0xc8201b1750, 0xc820181500, 0x0, 0x0, 0xc)
        /usr/lib/go-1.6/src/cmd/go/pkg.go:953 +0x4397
main.loadImport(0x9e1b98, 0x1, 0xc820016034, 0x29, 0x0, 0xc8201b1750, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/lib/go-1.6/src/cmd/go/pkg.go:377 +0x84e
main.loadPackage(0x9e1b98, 0x1, 0xc8201b1750, 0x0)
        /usr/lib/go-1.6/src/cmd/go/pkg.go:1639 +0x13d8
main.packagesAndErrors(0xc8201868e0, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go-1.6/src/cmd/go/pkg.go:1684 +0x531
main.packagesForBuild(0xc82000a110, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go-1.6/src/cmd/go/pkg.go:1700 +0x82
main.runBuild(0xc8aca0, 0xc82000a110, 0x0, 0x0)
        /usr/lib/go-1.6/src/cmd/go/build.go:442 +0x8d
main.main()
        /usr/lib/go-1.6/src/cmd/go/main.go:181 +0x783
godep: go exit status 2
Makefile:55: recipe for target 'server' failed
make: *** [server] Error 1
```

make error with all required github packages:
```
root@gluster01-portal:~/heketi# make server
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
godep go build -ldflags "-X main.HEKETI_VERSION=- -extldflags '-z relro -z now'" -o heketi
godep: [WARNING]: godep should only be used inside a valid go package directory and
godep: [WARNING]: may not function correctly. You are probably outside of your $GOPATH.
godep: [WARNING]:       Current Directory: /root/heketi
godep: [WARNING]:       $GOPATH: /root/heketi
# _/root/heketi
./main.go:139: cannot use heketiRouter (type *"github.com/gorilla/mux".Router) as type *"github.com/heketi/heketi/vendor/github.com/gorilla/mux".Router in argument to app.SetRoutes
godep: go exit status 2
Makefile:55: recipe for target 'server' failed
make: *** [server] Error 1
```

**Comment by lpabon** [comment]
Very interesting. I have never seen this.  Do you mind providing the OS type and version, and the Golang version?  I'll try to reproduce.

**Comment by naisanza** [comment]
@lpabon Sure! 

OS: Ubuntu 16.04 LXC running in Proxmox 4.4
Golang: 
```
root@gluster-test-build:~/heketi/src/github.com/heketi/heketi# aptitude show golang-go
Package: golang-go                
Version: 2:1.6.1+1ubuntu2
State: not installed
Priority: optional
Section: devel
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Uncompressed Size: 48.1 k
Depends: golang-1.6-go, golang-src (>= 2:1.6.1+1ubuntu2)
Recommends: golang-race-detector-runtime
Breaks: gccgo-5 (< 5.3.1-12~), gccgo-6 (< 6-20160319-1~), golang-go-darwin-386, golang-go-darwin-amd64, golang-go-freebsd-386, golang-go-freebsd-amd64,
        golang-go-freebsd-arm, golang-go-linux-386, golang-go-linux-amd64, golang-go-linux-arm, golang-go-netbsd-386, golang-go-netbsd-amd64,
        golang-go-windows-386, golang-go-windows-amd64, golang-go.tools (< 1:0.0~git20151026.0.0f9d71c-1~), golang-golang-x-tools (<
        1:0.0~git20151026.0.0f9d71c-1~)
Replaces: golang-go-darwin-386, golang-go-darwin-amd64, golang-go-freebsd-386, golang-go-freebsd-amd64, golang-go-freebsd-arm, golang-go-linux-386,
          golang-go-linux-amd64, golang-go-linux-arm, golang-go-netbsd-386, golang-go-netbsd-amd64, golang-go-windows-386, golang-go-windows-amd64,
          golang-go.tools (< 1:0.0~git20151026.0.0f9d71c-1~), golang-golang-x-tools (< 1:0.0~git20151026.0.0f9d71c-1~)
Description: Go programming language compiler, linker, compiled stdlib
 
Homepage: https://golang.org
```

But I removed it, and now building it in 16.10, and it works:

```
root@gluster-test-build:~/heketi/src/github.com/heketi/heketi# make 
godep go build -ldflags "-X main.HEKETI_VERSION=v3.0.0-104-g14686c0 -extldflags '-z relro -z now'" -o heketi
/bin/sh: 1: godep: Permission denied
Makefile:55: recipe for target 'server' failed
make: *** [server] Error 126
root@gluster-test-build:~/heketi/src/github.com/heketi/heketi# chmod -R +x /usr/local/bin
root@gluster-test-build:~/heketi/src/github.com/heketi/heketi# make 
godep go build -ldflags "-X main.HEKETI_VERSION=v3.0.0-104-g14686c0 -extldflags '-z relro -z now'" -o heketi
make[1]: Entering directory '/root/heketi/src/github.com/heketi/heketi/client/cli/go'
godep go build -ldflags "-X main.HEKETI_CLI_VERSION=v3.0.0-104-g14686c0 -extldflags '-z relro -z now'" -o heketi-cli
make[1]: Leaving directory '/root/heketi/src/github.com/heketi/heketi/client/cli/go'
```

I'll test it in 16.04 again and see if it fails again

**Comment by naisanza** [comment]
@lpabon I've been needing to download godep manually. `go get github.com/tools/godep` doesn't seem to do anything

Not sure how to solve that

**Comment by naisanza** [comment]
@lpabon Well, that's strange, it works in 16.04 now too

```
root@gluster-test-16:~/heketi/src/github.com/heketi/heketi# make server
godep go build -ldflags "-X main.HEKETI_VERSION=v3.0.0-104-g14686c0 -extldflags '-z relro -z now'" -o heketi
root@gluster-test-16:~/heketi/src/github.com/heketi/heketi# 
```

**Comment by lpabon** [comment]
Wow weird.  I'm glad it worked out.

**Comment by g0194776** [comment]
@naisanza Finally, how to solve it? I've met that building errors too.

```shelll
cannot use heketiRouter (type *"github.com/gorilla/mux".Router) as type *"github.com/heketi/heketi/vendor/github.com/gorilla/mux".Router in argument to app.SetRoutes
```

**Comment by naisanza** [comment]
@g0194776 I think it just fixed itself when I went to a newer version of Ubuntu

**Comment by g0194776** [comment]
@naisanza Sadly, the Travis CI ONLY supports few versions of LINUX :-(

Thank you.
